#!/bin/bash

version=1.8.1
wget https://jfrog.inaccel.com/artifactory/generic/packages/debian/inaccel_${version}_amd64.deb
dpkg --extract inaccel_${version}_amd64.deb tmp
rm inaccel_${version}_amd64.deb
mkdir --parents ~/.local/bin
mv tmp/usr/bin/inaccel ~/.local/bin/inaccel
rm --recursive tmp

wget --output-document ~/vision/data/bbb.mp4 http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_stereo_abl.mp4
