#!/bin/bash

version=0.1.0
wget --quiet https://dl.cloudsmith.io/public/inaccel/stable/deb/any-distro/pool/any-version/main/i/in/inaccel-cli_${version}/inaccel-cli_${version}_amd64.deb
dpkg --extract inaccel-cli_${version}_amd64.deb tmp
rm inaccel-cli_${version}_amd64.deb
mkdir --parents ~/.local/bin
mv tmp/usr/bin/inaccel ~/.local/bin/inaccel
rm --recursive tmp

wget --output-document ~/vision/data/bbb.mp4 --quiet http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_stereo_abl.mp4

install -m 0755 /dev/null ~/.local/bin/vitis
cat << EOF > ~/.local/bin/vitis
#!/bin/bash

platforms=("xilinx/aws-vu9p-f1/shell-v04261818_201920.2/aws" "xilinx/u200/xdma_201830.2" "xilinx/u250/xdma_201830.2" "xilinx/u280/xdma_201920.3")
PS3="Please select a platform [1-"\${#platforms[@]}"]: "
select platform in \${platforms[@]}
do
	case \${platform} in
		"xilinx/aws-vu9p-f1/shell-v04261818_201920.2/aws")
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/quantitativeFinance/blackScholes/1.1/4calculator
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/quantitativeFinance/monteCarlo/1.0/1Calibration_1PreSample_1Pricing1
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/vision/2.0/4stereoBM
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/vision/2.0/4colordetect
			break
			;;
		"xilinx/u200/xdma_201830.2")
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/quantitativeFinance/blackScholes/1.0/1calculator
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/quantitativeFinance/monteCarlo/1.0/1Calibration_1PreSample_1Pricing1
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/vision/1.0/1stereoBM
			break
			;;
		"xilinx/u250/xdma_201830.2")
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/quantitativeFinance/monteCarlo/1.0/1Calibration_1PreSample_1Pricing1_1Pricing2
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/vision/1.0/1stereoBM
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/vision/2.0/4colordetect
			break
			;;
		"xilinx/u280/xdma_201920.3")
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/vision/1.0/1stereoBM
			inaccel bitstream install https://store.inaccel.com/artifactory/bitstreams/\${platform}/com/xilinx/vitis/vision/2.0/4colordetect
			break
			;;
		*) echo "invalid platform id \${REPLY}";;
	esac
done
EOF
